In [1]:
import pandas as pd

In [4]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.22.4 in c:\users\pc\anaconda3\envs\bert\lib\site-packages (from pandas) (1.23.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pc\anaconda3\envs\bert\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2026.4-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\pc\anaconda3\envs\bert\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.3 MB 3.7 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/11.3 MB 3.7 MB/s eta 0:00:03
   ------- -------------------------------- 2.1/11.3 MB 3.6 MB/s eta 0:00:03
   ---------- ----------------------------- 2.9/11.3 MB 3.4 MB/s eta 0:00:03
   ------------ --------------------------- 3.7/11.3 MB 3.4 MB/s eta 0:00:03
   -------------- ------------------------- 4.2/11.3 MB 3.4 MB/s eta 0:00:03
   ----------------- ---------------------- 5.0/11.3 MB 3.4 MB/s eta 0:00:02
   -------------------- ------------------- 5.8/11.3 MB 3.4 MB/s eta 0:00:02
   ---------------------- ----------------- 6.3/11.3 MB 3.3 MB/s eta 0:00:02
   ---------------------- ----------------- 6.3/11.3 MB 3.3 MB/s eta 0:00:02
   ----------------------- ---------------- 6.6/11.3 MB 2.8 MB/s eta 0:00:02
   ------------------------ --------------- 7.1/11.3 MB 2.8 MB/s eta 0:00:02
   ------------------------- -------------- 7.3/11.3 MB 2.8 MB/s eta 0:00:02
   -------------------------- ------------- 7.6/11.3 MB 2.6 MB/s eta 0:00:02
   -------------------------- ------------- 7.6/11.3 MB 2.6 MB/s eta 0:00:02
   --------------------------- ------------ 7.9/11.3 MB 2.3 MB/s eta 0:00:02
   --------------------------- ------------ 7.9/11.3 MB 2.3 MB/s eta 0:00:02
   ----------------------------- ---------- 8.4/11.3 MB 2.1 MB/s eta 0:00:02
   ------------------------------ --------- 8.7/11.3 MB 2.1 MB/s eta 0:00:02
   ------------------------------- -------- 8.9/11.3 MB 2.0 MB/s eta 0:00:02
   ------------------------------- -------- 8.9/11.3 MB 2.0 MB/s eta 0:00:02
   --------------------------------- ------ 9.4/11.3 MB 1.9 MB/s eta 0:00:01
   --------------------------------- ------ 9.4/11.3 MB 1.9 MB/s eta 0:00:01
   ---------------------------------- ----- 9.7/11.3 MB 1.9 MB/s eta 0:00:01
   ----------------------------------- ---- 10.0/11.3 MB 1.8 MB/s eta 0:00:01
   ------------------------------------ --- 10.2/11.3 MB 1.8 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.3 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.3 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 1.8 MB/s  0:00:06
Downloading pytz-2026.4-py2.py3-none-any.whl (506 kB)
Downloading tzdata-2026.4-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pandas

   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed pandas-2.3.3 pytz-2026.4 tzdata-2026.4

WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored

In [2]:
df=pd.read_csv("C:\\Users\\pc\\Downloads\\spam.csv")

In [4]:
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
df.groupby("Category").describe()

         Message                                                            \
           count unique                                                top
Category
ham         4825   4516                             Sorry, I'll call later
spam         747    641  Please call our customer service representativ...


         freq
Category
ham        30
spam        4

In [3]:
df['spam']=df["Category"].apply(lambda x:1 if x=='spam' else 0)

In [7]:
df

     Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [4]:
import tensorflow as tf

In [5]:
import tensorflow_hub as hub

c:\Users\pc\anaconda3\envs\bert\lib\site-packages\tensorflow_hub\__init__.py:61: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import parse_version

In [10]:
!pip install tensorflow_hub

Collecting tensorflow_hub
  Downloading tensorflow_hub-0.16.1-py2.py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: numpy>=1.12.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow_hub) (2.3.5)
Requirement already satisfied: protobuf>=3.19.6 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow_hub) (7.34.1)
Collecting tf-keras>=2.14.1 (from tensorflow_hub)
  Downloading tf_keras-2.21.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: tensorflow<2.22,>=2.21 in c:\users\pc\anaconda3\lib\site-packages (from tf-keras>=2.14.1->tensorflow_hub) (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (3.4.0)
Requirement already satisfied: packaging in c:\users\pc\anaconda3\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (25.0)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (2.32.5)
Requirement already satisfied: setuptools in c:\users\pc\anaconda3\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (1.80.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (3.14.1)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\pc\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pc\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\pc\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pc\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (2026.4.22)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\pc\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (0.45.1)
Requirement already satisfied: rich in c:\users\pc\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (14.2.0)
Requirement already satisfied: namex in c:\users\pc\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (0.1.0)
Requirement already satisfied: optree in c:\users\pc\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (0.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\pc\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\pc\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\pc\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras>=2.14.1->tensorflow_hub) (0.1.2)
Downloading tensorflow_hub-0.16.1-py2.py3-none-any.whl (30 kB)
Downloading tf_keras-2.21.0-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------------ --------------------------- 0.5/1.7 MB 2.0 MB/s eta 0:00:01
   ------------------ --------------------- 0.8/1.7 MB 2.1 MB/s eta 0:00:01
   ------------------ --------------------- 0.8/1.7 MB 2.1 MB/s eta 0:00:01
   ------------------------ --------------- 1.0/1.7 MB 1.1 MB/s eta 0:00:01
   ------------------------------------- -- 1.6/1.7 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 1.3 MB/s  0:00:01
Installing collected packages: tf-keras, tensorflow_hub

   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   ---------------------------------------- 0/2 [tf-keras]
   -------------------- ------------------- 1/2 [tensorflow_hub]
   ---------------------------------------- 2/2 [tensorflow_hub]

Successfully installed tensorflow_hub-0.16.1 tf-keras-2.21.0

WARNING: Cache entry deserialization failed, entry ignored

In [6]:
import tensorflow_text as text

In [7]:
import tensorflow_hub as hub

In [8]:
bert_preprocess=hub.KerasLayer("https://kaggle.com/models/tensorflow/bert/TensorFlow2/en-uncased-preprocess/3")

In [9]:
bert_encoder=hub.KerasLayer("https://www.kaggle.com/models/tensorflow/bert/TensorFlow2/en-uncased-l-12-h-768-a-12/4")

In [10]:
import tensorflow_text as text

In [16]:
!pip install tensorflow_text

ERROR: Could not find a version that satisfies the requirement tensorflow_text (from versions: none)
ERROR: No matching distribution found for tensorflow_text

In [13]:
def get_sentence_embeding(sentences):
    preprocessed_text=bert_preprocess([sentences])
    return bert_encoder(preprocessed_text)['pooled_output'][0]

In [ ]:
get_sentence_embeding(["Free discount today","Bhavin, are you up for a volleyball game tomorrow?"])

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.9266154 , -0.49609736, -0.84670085, ..., -0.493707  ,
        -0.78827727,  0.93381494],
       [-0.82059693, -0.5209497 , -0.95245343, ..., -0.8804194 ,
        -0.7053685 ,  0.8252004 ]], dtype=float32)>

In [ ]:
df['encoding']=df["Message"].apply(get_sentence_embeding)